repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: mixed-line-ending
        args: ['--fix=lf']
        exclude: \.(bat|cmd|ps1)$

  - repo: local
    hooks:
      - id: format-and-check
        name: Format & Recheck
        entry: python3 scripts/run_with_fallback.py gradle spotlessApply spotlessCheck
        language: system
        pass_filenames: false
        types_or: [kotlin]

      - id: build
        name: Build
        entry: python3 scripts/run_with_fallback.py gradle assemble
        language: system
        pass_filenames: false
        types_or: [kotlin]

      - id: test
        name: Test
        entry: python3 scripts/run_with_fallback.py gradle allTests
        language: system
        pass_filenames: false
        types_or: [kotlin]

      - id: lint
        name: Lint (Verify)
        entry: python3 scripts/run_with_fallback.py gradle check
        language: system
        pass_filenames: false
        types_or: [kotlin]

      - id: test-swagger-2
        name: Swagger 2.0 Petstore test
        entry: python3 scripts/test_sdk.py src/test/resources/stripe.json /v1
        language: system
        pass_filenames: false
        always_run: true

      - id: test-openapi-3
        name: OpenAPI 3.2.0 Petstore test
        entry: python3 scripts/test_sdk.py src/test/resources/mega_spec.json /api/v3
        language: system
        pass_filenames: false
        always_run: true

      - id: test-server-and-client-swagger-2
        name: Swagger 2.0 Server and Client test
        entry: python3 scripts/test_server_and_client.py src/test/resources/stripe.json
        language: system
        pass_filenames: false
        always_run: true

      - id: test-server-and-client-openapi-3
        name: OpenAPI 3.2.0 Server and Client test
        entry: python3 scripts/test_server_and_client.py src/test/resources/mega_spec.json
        language: system
        pass_filenames: false
        always_run: true

      - id: build-wasm
        name: Build WASM
        entry: python3 scripts/run_with_fallback.py build_wasm
        language: system
        pass_filenames: false
        always_run: true

      - id: update-badges
        name: Update Badges
        entry: python3 scripts/run_with_fallback.py python scripts/update_badges.py
        language: system
        pass_filenames: false
        always_run: true
