import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.required
import com.github.ajalt.clikt.parameters.types.choice
import scaffold.ScaffoldGenerator
import domain.Info
import domain.Contact
import domain.License
import java.io.File
import psi.DtoParser
import psi.NetworkParser
import openapi.OpenApiAssembler
import openapi.OpenApiWriter

/**
 * Root command for the cdd-kotlin CLI.
 */
class CddKotlin : CliktCommand(name = "cdd_kotlin", help = "OpenAPI ↔ Kotlin") {
    /** Run method for the base command. */
    override fun run() {}
}

/**
 * Subcommand to generate a KMP client from an OpenAPI spec.
 */
class FromOpenApi : CliktCommand(name = "from_openapi", help = "Generate Client SDK services from an OpenAPI specification") {
    /** Configuration file path. */
    val config by option("-c", "--config", help = "Path to a configuration file")
    /** Input OpenAPI specification file or URL. */
    val input by option("-i", "--input", help = "Path or URL to the OpenAPI spec (overrides config)")
    /** Output directory path. */
    val output by option("-o", "--output", help = "Output directory for generated files (overrides config)")
    /** Name of the generated client. */
    val clientName by option("--clientName", help = "Name for the generated client")
    /** Target framework for code generation. */
    val framework by option("--framework", help = "Target framework (choices: \"ktor\", \"okhttp\", default: \"ktor\")").default("ktor")
    /** Date type to be used in models. */
    val dateType by option("--dateType", help = "Date type to use (choices: \"string\", \"Instant\")")
    /** Enum style to be used. */
    val enumStyle by option("--enumStyle", help = "Style for enums (choices: \"enum\", \"sealed\")")
    /** Disable generation of network services. */
    val noGenerateServices by option("--no-generate-services", help = "Disable generation of services").flag()
    /** Disable generation of unit tests for services. */
    val noTestsForService by option("--no-tests-for-service", help = "Disable generation of tests for services").flag()

    /** Executes the from_openapi generator logic. */
    override fun run() {
        val outDir = if (output != null) File(output!!) else File("generated-project")
        val generator = ScaffoldGenerator()
        val appInfo = Info(
            title = clientName ?: "GeneratedApp",
            version = "1.0.0",
            summary = "An example KMP application generated by cdd-kotlin",
            contact = Contact("Support", "support@example.com", "https://example.com"),
            license = License("Apache 2.0", "Apache-2.0")
        )

        try { 
            val apiGenOutput = File(outDir, "composeApp/src/commonMain/kotlin")
            if (input != null) {
                psi.ApiGenerator.generate(input!!, apiGenOutput, "com.example.auto")
            }
            generator.generate(
                outputDirectory = outDir,
                projectName = clientName ?: "MyGeneratedApp",
                packageName = "com.example.auto",
                info = appInfo
            )
            println("Success! Generated project into ${outDir.absolutePath}")
        } catch (e: Exception) {
            println("Failed to generate scaffold:")
            e.printStackTrace()
        }
    }
}

/**
 * Subcommand to parse Kotlin code and generate an OpenAPI spec.
 */
class ToOpenApi : CliktCommand(name = "to_openapi", help = "Generate an OpenAPI specification from Kotlin code") {
    /** Path to a file or directory containing the generated project. */
    val file by option("-f", "--file", help = "Path to a snapshot file or a generated output directory").required()
    /** Format of the output OpenAPI specification. */
    val format by option("--format", help = "Output format for the OpenAPI spec").choice("json", "yaml").default("yaml")

    /** Executes the to_openapi parser logic. */
    override fun run() {
        val srcDir = File(file)
        if (!srcDir.exists()) {
            println("File or directory not found: ${srcDir.absolutePath}")
            return
        }

        try {
            val dtoParser = DtoParser()
            val networkParser = NetworkParser()
            val assembler = OpenApiAssembler()
            val writer = OpenApiWriter()
            
            val sourceCode = if (srcDir.isDirectory) {
                srcDir.walk().filter { it.isFile && it.extension == "kt" }.joinToString("\n") { it.readText() }
            } else {
                srcDir.readText()
            }

            val schemas = dtoParser.parse(sourceCode)
            val endpoints = networkParser.parse(sourceCode)

            val definition = assembler.assemble(
                info = Info(title = "Generated API", version = "1.0.0"),
                schemas = schemas,
                endpoints = endpoints
            )

            val output = if (format == "json") {
                writer.writeJson(definition)
            } else {
                writer.writeYaml(definition)
            }

            println(output)
        } catch (e: Exception) {
            println("❌ to_openapi failed: ${e.message}")
            e.printStackTrace()
        }
    }
}

/**
 * Main entry point for the cdd-kotlin executable.
 * @param args The command line arguments
 */
fun main(args: Array<String>) {
    CddKotlin().subcommands(FromOpenApi(), ToOpenApi()).main(args)
}
