import domain.Info
import domain.Contact
import domain.License
import scaffold.ScaffoldGenerator
import java.io.File

fun main() {
    val generator = ScaffoldGenerator()

    // We generate the scaffold into a folder named "generated-project" inside this project
    // just for demonstration purposes.
    val outputDir = File("generated-project")

    println("Generating KMP Scaffold into: ${outputDir.absolutePath}...")

    // Create an OpenAPI Info object (Mocking input from a Specification)
    val appInfo = Info(
        title = "My Generated App",
        version = "2.4.1",
        summary = "An example KMP application generated by cdd-kotlin",
        contact = Contact(
            name = "Support Team",
            email = "support@example.com",
            url = "https://example.com/support"
        ),
        license = License(
            name = "Apache 2.0",
            identifier = "Apache-2.0"
        )
    )

    try {
        generator.generate(
            outputDirectory = outputDir,
            projectName = "MyGeneratedApp",
            packageName = "com.example.auto",
            info = appInfo
        )
        println("Success! Open 'generated-project' in IntelliJ to see the result.")
    } catch (e: Exception) {
        println("Failed to generate scaffold:")
        e.printStackTrace()
    }
}
