import domain.Contact
import domain.Info
import domain.License
import openapi.OpenApiDocument
import openapi.OpenApiParser
import scaffold.ScaffoldGenerator

/**
 * Main entry point for the cdd-kotlin CLI.
 *
 * @param args Command-line arguments.
 */
fun main(args: Array<String>) {
  val exitCode = runCli(args)
  if (exitCode != 0) {
    throw RuntimeException("CLI exited with code $exitCode")
  }
}

/**
 * Runs the CLI logic and returns an exit code.
 *
 * @param args Command-line arguments.
 * @return the exit code (0 for success, non-zero for failure).
 */
fun runCli(args: Array<String>): Int {
  try {
    if (args.isEmpty()) {
      println("cdd-kotlin CLI")
      return 0
    }

    val command = if (args.size > 1 && args[0] == "from_openapi") args[1] else args[0]
    if (command == "demo") {
      val generator = ScaffoldGenerator()
      val outputDir = (getEnvVar("PWD") ?: ".") + "/generated-project"
      println("Generating KMP Scaffold into: ${outputDir}...")
      val appInfo =
          Info(
              title = "My Generated App",
              version = "2.4.1",
              summary = "An example KMP application generated by cdd-kotlin",
              contact =
                  Contact(
                      name = "Support Team",
                      email = "support@example.com",
                      url = "https://example.com/support"),
              license = License(name = "Apache 2.0", identifier = "Apache-2.0"))
      try {
        generator.generate(outputDir, "MyGeneratedApp", "com.example.auto", appInfo)
        println("Success! Open 'generated-project' in IntelliJ to see the result.")
      } catch (e: Exception) {
        println("Failed to generate scaffold:")
        e.printStackTrace()
        return 1
      }
      return 0
    }

    if (command == "to_sdk") {
      var outputDir = "out"
      var inputFile = ""
      var noGithubActions = false
      var noInstallablePackage = false
      var tests = false
      var i = 1
      while (i < args.size) {
        when (args[i]) {
          "-o",
          "--output" -> if (i + 1 < args.size) outputDir = args[++i]
          "-i",
          "--input" -> if (i + 1 < args.size) inputFile = args[++i]
          "--no-github-actions" -> noGithubActions = true
          "--no-installable-package" -> noInstallablePackage = true
          "--tests" -> tests = true
        }
        i++
      }

      if (inputFile.isEmpty()) {
        inputFile = getEnvVar("CDD_INPUT") ?: getEnvVar("INPUT") ?: ""
      }

      if (inputFile.isEmpty()) {
        println("Missing -i <spec.json>")
        return 1
      }

      try {
        val config =
            org.cdd.Config(
                inputPath = inputFile,
                outputDir = outputDir,
                noGithubActions = noGithubActions,
                noInstallablePackage = noInstallablePackage,
                tests = tests)
        org.cdd.CddGenerator.generateSdk(config)
      } catch (e: Exception) {
        println("Failed to generate SDK:")
        e.printStackTrace()
        return 1
      }
      return 0
    }

    if (command == "to_openapi") {
      var outputDir = "out.json"
      var inputFile = ""
      var i = 1
      while (i < args.size) {
        when (args[i]) {
          "-o",
          "--output" -> if (i + 1 < args.size) outputDir = args[++i]
          "-i",
          "--input" -> if (i + 1 < args.size) inputFile = args[++i]
        }
        i++
      }

      if (inputFile.isEmpty()) {
        println("Missing -i <src>")
        return 1
      }

      try {
        generateOpenApi(inputFile, outputDir)
      } catch (e: Exception) {
        println("Failed to generate OpenAPI:")
        e.printStackTrace()
        return 1
      }
      return 0
    }

    if (command == "to_docs_json") {

      var inputFile = ""
      var noImports = false
      var noWrapping = false

      var i = 1
      while (i < args.size) {
        when (args[i]) {
          "-i",
          "--input" -> if (i + 1 < args.size) inputFile = args[++i]
          "--no-imports" -> noImports = true
          "--no-wrapping" -> noWrapping = true
        }
        i++
      }

      if (inputFile.isEmpty()) {
        inputFile = getEnvVar("CDD_INPUT") ?: getEnvVar("INPUT") ?: ""
      }

      if (inputFile.isEmpty()) {
        println("Missing -i <spec.json>")
        return 1
      }

      val jsonStr = readFile(inputFile)
      val parser = OpenApiParser()

      val result =
          try {
            parser.parseDocumentString(jsonStr)
          } catch (e: Throwable) {
            println("PARSE ERROR: " + e.message)
            throw e
          }

      val doc =
          when (result) {
            is OpenApiDocument.OpenApi -> result.definition
            else -> {
              println("Not an OpenAPI document")
              return 1
            }
          }

      val endpoints = mutableMapOf<String, Map<String, String>>()

      for ((path, pathItem) in doc.paths) {
        val methods =
            mapOf(
                "get" to pathItem.get,
                "put" to pathItem.put,
                "post" to pathItem.post,
                "delete" to pathItem.delete,
                "options" to pathItem.options,
                "head" to pathItem.head,
                "patch" to pathItem.patch,
                "trace" to pathItem.trace)

        val methodMap = mutableMapOf<String, String>()

        for ((methodName, operation) in methods) {
          if (operation == null) continue

          val opId =
              operation.operationId
                  ?: "${methodName}${path.replace("/", "").replace("{", "").replace("}", "")}"

          val sb = StringBuilder()

          if (!noImports) {
            sb.append("import io.ktor.client.*\nimport io.ktor.client.request.*\n\n")
          }

          if (!noWrapping) {
            sb.append("suspend fun main() {\n    val client = HttpClient()\n")
          }

          val indent = if (noWrapping) "" else "    "
          sb.append(
              "${indent}val response = client.${methodName}(\"https://api.example.com$path\") {\n")
          sb.append("$indent    // Add parameters and body here\n")
          sb.append("$indent}\n")
          sb.append("${indent}println(response)\n")

          if (!noWrapping) {
            sb.append("}\n")
          }

          methodMap[methodName] = sb.toString()
        }

        if (methodMap.isNotEmpty()) {
          endpoints[path] = methodMap
        }
      }

      val sb = StringBuilder()
      sb.append("{\n  \"endpoints\": {\n")
      var pathIndex = 0
      for ((path, methods) in endpoints) {
        sb.append("    \"$path\": {\n")
        var methodIndex = 0
        for ((methodName, code) in methods) {
          val escapedCode = code.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
          sb.append("      \"$methodName\": \"$escapedCode\"")
          if (methodIndex < methods.size - 1) sb.append(",")
          sb.append("\n")
          methodIndex++
        }
        sb.append("    }")
        if (pathIndex < endpoints.size - 1) sb.append(",")
        sb.append("\n")
        pathIndex++
      }
      sb.append("  }\n}")
      println(sb.toString())
      return 0
    }

    println("Unknown command: $command")
    return 1
  } catch (e: Throwable) {
    println("Execution failed: " + e.message)
    e.printStackTrace()
    return 1
  }
}
