

import writeToFile

import openapi.OpenApiParser
import openapi.OpenApiDocument
import domain.EndpointDefinition
import domain.HttpMethod
import domain.Info
import domain.Contact
import domain.License
import scaffold.ScaffoldGenerator

/**
 * Main entry point for the cdd-kotlin CLI.
 * 
 * @param args Command-line arguments.
 */
fun main(args: Array<String>) {
    val exitCode = runCli(args)
    if (exitCode != 0) {
        throw RuntimeException("CLI exited with code $exitCode")
    }
}

/**
 * Runs the CLI logic and returns an exit code.
 * 
 * @param args Command-line arguments.
 * @return the exit code (0 for success, non-zero for failure).
 */
fun runCli(args: Array<String>): Int {
    try {
        if (args.isEmpty()) {
            println("cdd-kotlin CLI")
            return 0
        }

        val command = if (args.size > 1 && args[0] == "from_openapi") args[1] else args[0]
        if (command == "demo") {
        val generator = ScaffoldGenerator()
        val outputDir = (getEnvVar("PWD") ?: ".") + "/generated-project"
        println("Generating KMP Scaffold into: ${outputDir}...")
        val appInfo = Info(
            title = "My Generated App",
            version = "2.4.1",
            summary = "An example KMP application generated by cdd-kotlin",
            contact = Contact(name = "Support Team", email = "support@example.com", url = "https://example.com/support"),
            license = License(name = "Apache 2.0", identifier = "Apache-2.0")
        )
        try {
            generator.generate(outputDir, "MyGeneratedApp", "com.example.auto", appInfo)
            println("Success! Open 'generated-project' in IntelliJ to see the result.")
        } catch (e: Exception) {
            println("Failed to generate scaffold:")
            e.printStackTrace()
            return 1
        }
        return 0
    }

    
    if (command == "to_sdk") {
        var outputDir = "out"
        var inputFile = ""
        var i = 1
        while (i < args.size) {
            when (args[i]) {
                "-o", "--output" -> if (i + 1 < args.size) outputDir = args[++i]
                "-i", "--input" -> if (i + 1 < args.size) inputFile = args[++i]
            }
            i++
        }

        if (inputFile.isEmpty()) {
            inputFile = getEnvVar("CDD_INPUT") ?: getEnvVar("INPUT") ?: ""
        }

        if (inputFile.isEmpty()) {
            println("Missing -i <spec.json>")
            return 1
        }

        val jsonStr = readFile(inputFile)
        val parser = OpenApiParser()
        val result = try { parser.parseDocumentString(jsonStr) } catch(e: Throwable) { println("PARSE ERROR: " + e.message); throw e }

        val doc = when (result) {
            is OpenApiDocument.OpenApi -> result.definition
            else -> {
                println("Not an OpenAPI document")
                return 1
            }
        }

        println("Generating Kotlin SDK...")

        // Generate Models.kt
        val modelsSb = StringBuilder()
        modelsSb.append("package org.example\n\n")
        modelsSb.append("import kotlinx.serialization.Serializable\n\n")
        
        doc.components?.schemas?.forEach { (name, schema) ->
            modelsSb.append("@Serializable\n")
            modelsSb.append("data class $name(\n")
            val props = mutableListOf<String>()
            schema.properties.forEach { (propName, propDef) ->
                // simplified type mapping
                var kotlinType = "String"
                if (propDef.types.contains("integer") || propDef.type == "integer") kotlinType = "Int"
                else if (propDef.types.contains("boolean") || propDef.type == "boolean") kotlinType = "Boolean"
                else if (propDef.types.contains("number") || propDef.type == "number") kotlinType = "Double"
                else if (propDef.types.contains("array") || propDef.type == "array") {
                    kotlinType = "List<Any>" // simplified
                } else if (propDef.ref != null) {
                    kotlinType = propDef.ref.split("/").last()
                }
                
                if (!schema.required.contains(propName)) {
                    kotlinType += "? = null"
                }
                props.add("    val $propName: $kotlinType")
            }
            modelsSb.append(props.joinToString(",\n"))
            modelsSb.append("\n)\n\n")
        }
        
        if (doc.components?.schemas?.isNotEmpty() == true) {
            writeToFile("$outputDir/Models.kt", modelsSb.toString())
        }

        // Generate Client.kt
        val clientSb = StringBuilder()
        clientSb.append("package org.example\n\n")
        clientSb.append("import io.ktor.client.*\n")
        clientSb.append("import io.ktor.client.request.*\n")
        clientSb.append("import io.ktor.client.statement.*\n\n")
        clientSb.append("class Client(val baseUrl: String = \"https://api.example.com\") {\n")
        clientSb.append("    val client = HttpClient()\n\n")
        
        for ((path, pathItem) in doc.paths) {
            val methods = mapOf(
                "get" to pathItem.get,
                "put" to pathItem.put,
                "post" to pathItem.post,
                "delete" to pathItem.delete,
                "options" to pathItem.options,
                "head" to pathItem.head,
                "patch" to pathItem.patch,
                "trace" to pathItem.trace
            )
            for ((methodName, operation) in methods) {
                if (operation == null) continue
                
                val opId = operation.operationId ?: "${methodName}${path.replace("/", "").replace("{", "").replace("}", "")}"
                
                var urlPath = path
                urlPath = urlPath.replace(Regex("\\{([^}]+)\\}")) { matchResult ->
                    "$" + "{${matchResult.groupValues[1]}}"
                }
                
                val paramsStr = mutableListOf<String>()
                val pathParams = Regex("\\{([^}]+)\\}").findAll(path).map { it.groupValues[1] }.toList()
                for (param in pathParams) {
                    paramsStr.add("$param: String")
                }
                
                val arguments = paramsStr.joinToString(", ")
                
                clientSb.append("    suspend fun $opId($arguments): HttpResponse {\n")
                clientSb.append("        return client.${methodName}(\"\$baseUrl$urlPath\") {\n")
                clientSb.append("            // Add parameters and body here\n")
                clientSb.append("        }\n")
                clientSb.append("    }\n\n")
            }
        }
        clientSb.append("}\n")

        writeToFile("$outputDir/Client.kt", clientSb.toString())
        return 0
    }

    if (command == "to_docs_json") {

        var inputFile = ""
        var noImports = false
        var noWrapping = false

        var i = 1
        while (i < args.size) {
            when (args[i]) {
                "-i", "--input" -> if (i + 1 < args.size) inputFile = args[++i]
                "--no-imports" -> noImports = true
                "--no-wrapping" -> noWrapping = true
            }
            i++
        }



        if (inputFile.isEmpty()) {
            inputFile = getEnvVar("CDD_INPUT") ?: getEnvVar("INPUT") ?: ""
        }



        if (inputFile.isEmpty()) {
            println("Missing -i <spec.json>")
            return 1
        }


        val jsonStr = readFile(inputFile)
        val parser = OpenApiParser()

        val result = try { parser.parseDocumentString(jsonStr) } catch(e: Throwable) { println("PARSE ERROR: " + e.message); throw e }

        val doc = when (result) {
            is OpenApiDocument.OpenApi -> result.definition
            else -> {
                println("Not an OpenAPI document")
                return 1
            }
        }

        val endpoints = mutableMapOf<String, Map<String, String>>()

        for ((path, pathItem) in doc.paths) {
            val methods = mapOf(
                "get" to pathItem.get,
                "put" to pathItem.put,
                "post" to pathItem.post,
                "delete" to pathItem.delete,
                "options" to pathItem.options,
                "head" to pathItem.head,
                "patch" to pathItem.patch,
                "trace" to pathItem.trace
            )

            val methodMap = mutableMapOf<String, String>()

            for ((methodName, operation) in methods) {
                if (operation == null) continue

                val opId = operation.operationId ?: "${methodName}${path.replace("/", "").replace("{", "").replace("}", "")}"

                val sb = StringBuilder()

                if (!noImports) {
                    sb.append("import io.ktor.client.*\nimport io.ktor.client.request.*\n\n")
                }

                if (!noWrapping) {
                    sb.append("suspend fun main() {\n    val client = HttpClient()\n")
                }

                val indent = if (noWrapping) "" else "    "
                sb.append("${indent}val response = client.${methodName}(\"https://api.example.com$path\") {\n")
                sb.append("$indent    // Add parameters and body here\n")
                sb.append("$indent}\n")
                sb.append("${indent}println(response)\n")

                if (!noWrapping) {
                    sb.append("}\n")
                }

                methodMap[methodName] = sb.toString()
            }

            if (methodMap.isNotEmpty()) {
                endpoints[path] = methodMap
            }
        }

        val sb = StringBuilder()
        sb.append("{\n  \"endpoints\": {\n")
        var pathIndex = 0
        for ((path, methods) in endpoints) {
            sb.append("    \"$path\": {\n")
            var methodIndex = 0
            for ((methodName, code) in methods) {
                val escapedCode = code.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n")
                sb.append("      \"$methodName\": \"$escapedCode\"")
                if (methodIndex < methods.size - 1) sb.append(",")
                sb.append("\n")
                methodIndex++
            }
            sb.append("    }")
            if (pathIndex < endpoints.size - 1) sb.append(",")
            sb.append("\n")
            pathIndex++
        }
        sb.append("  }\n}")
        println(sb.toString())
        return 0
    }
    
        println("Unknown command: $command")
        return 1
    } catch (e: Throwable) {
        println("Execution failed: " + e.message)
        e.printStackTrace()
        return 1
    }
}
