package cdd

import cdd.openapi.*
import cdd.classes.*
import cdd.routes.*
import cdd.docstrings.*
import cdd.shared.*
import cdd.scaffold.*


import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.required
import com.github.ajalt.clikt.parameters.types.choice
import com.github.ajalt.clikt.parameters.options.versionOption
import java.io.File

/**
 * Root command for the cdd-kotlin CLI.
 */
class CddKotlin : CliktCommand(name = "cdd_kotlin", help = "OpenAPI ↔ Kotlin") {
    init {
        versionOption("1.0.0")
    }
    /** Run method for the base command. */
    override fun run() {}
}

/**
 * Subcommand to generate a KMP client from an OpenAPI spec.
 */
class FromOpenApi : CliktCommand(name = "from_openapi", help = "Generate Client SDK services from an OpenAPI specification") {
    /** Configuration file path. */
    val config by option("-c", "--config", help = "Path to a configuration file")
    /** Input OpenAPI specification file or URL. */
    val input by option("-i", "--input", help = "Path or URL to the OpenAPI spec (overrides config)")
    /** Output directory path. */
    val output by option("-o", "--output", help = "Output directory for generated files (overrides config)")
    /** Name of the generated client. */
    val clientName by option("--clientName", help = "Name for the generated client")
    /** Target framework for code generation. */
    val framework by option("--framework", help = "Target framework (choices: \"ktor\", \"okhttp\", default: \"ktor\")").default("ktor")
    /** Date type to be used in models. */
    val dateType by option("--dateType", help = "Date type to use (choices: \"string\", \"Instant\")")
    /** Enum style to be used. */
    val enumStyle by option("--enumStyle", help = "Style for enums (choices: \"enum\", \"sealed\")")
    /** Disable generation of network services. */
    val noGenerateServices by option("--no-generate-services", help = "Disable generation of services").flag()
    /** Disable generation of unit tests for services. */
    val noTestsForService by option("--no-tests-for-service", help = "Disable generation of tests for services").flag()

    /** Executes the from_openapi generator logic. */
    override fun run() {
        val outDir = if (output != null) File(output!!) else File("generated-project")
        val generator = ScaffoldGenerator()
        val appInfo = Info(
            title = clientName ?: "GeneratedApp",
            version = "1.0.0",
            summary = "An example KMP application generated by cdd-kotlin",
            contact = Contact("Support", "support@example.com", "https://example.com"),
            license = License("Apache 2.0", "Apache-2.0")
        )

        try { 
            val apiGenOutput = File(outDir, "composeApp/src/commonMain/kotlin")
            if (input != null) {
                cdd.openapi.ApiGenerator.generate(input!!, apiGenOutput, "com.example.auto")
            }
            generator.generate(
                outputDirectory = outDir,
                projectName = clientName ?: "MyGeneratedApp",
                packageName = "com.example.auto",
                info = appInfo
            )
            println("Success! Generated project into ${outDir.absolutePath}")
        } catch (e: Exception) {
            println("Failed to generate scaffold:")
            e.printStackTrace()
        }
    }
}

/**
 * Subcommand to parse Kotlin code and generate an OpenAPI spec.
 */
class ToOpenApi : CliktCommand(name = "to_openapi", help = "Generate an OpenAPI specification from Kotlin code") {
    /** Path to a file or directory containing the generated project. */
    val file by option("-f", "--file", help = "Path to a snapshot file or a generated output directory").required()
    /** Format of the output OpenAPI specification. */
    val format by option("--format", help = "Output format for the OpenAPI spec").choice("json", "yaml").default("yaml")

    /** Executes the to_openapi parser logic. */
    override fun run() {
        val srcDir = File(file)
        if (!srcDir.exists()) {
            println("File or directory not found: ${srcDir.absolutePath}")
            return
        }

        try {
            val dtoParser = DtoParser()
            val networkParser = NetworkParser()
            val assembler = OpenApiAssembler()
            val writer = OpenApiWriter()
            
            val sourceCode = if (srcDir.isDirectory) {
                srcDir.walk().filter { it.isFile && it.extension == "kt" }.joinToString("\n") { it.readText() }
            } else {
                srcDir.readText()
            }

            val schemas = dtoParser.parse(sourceCode)
            val endpoints = networkParser.parse(sourceCode)

            val definition = assembler.assemble(
                info = Info(title = "Generated API", version = "1.0.0"),
                schemas = schemas,
                endpoints = endpoints
            )

            val output = if (format == "json") {
                writer.writeJson(definition)
            } else {
                writer.writeYaml(definition)
            }

            println(output)
        } catch (e: Exception) {
            println("❌ to_openapi failed: ${e.message}")
            e.printStackTrace()
        }
    }
}

/**
 * Subcommand to merge an OpenAPI spec into an existing Kotlin codebase.
 */
class MergeOpenApi : CliktCommand(name = "merge_openapi", help = "Merge an OpenAPI specification into an existing Kotlin codebase") {
    /** Input OpenAPI specification file. */
    val spec by option("-s", "--spec", help = "Path to the new OpenAPI specification file").required()
    /** Directory containing the existing Kotlin codebase. */
    val dir by option("-d", "--dir", help = "Directory containing the existing Kotlin codebase").required()

    /** Executes the merge_openapi logic. */
    override fun run() {
        val specFile = File(spec)
        val srcDir = File(dir)
        
        if (!specFile.exists()) {
            println("Spec file not found: ${specFile.absolutePath}")
            return
        }
        if (!srcDir.exists() || !srcDir.isDirectory) {
            println("Source directory not found or is not a directory: ${srcDir.absolutePath}")
            return
        }

        org.jetbrains.kotlin.cli.common.environment.setIdeaIoUseFallback()
        val disposable = org.jetbrains.kotlin.com.intellij.openapi.util.Disposer.newDisposable()

        try {
            cdd.shared.PsiInfrastructure.project // initialize
            val parser = cdd.openapi.OpenApiParser()
            val document = parser.parseFile(specFile)
            
            val dtoMerger = cdd.classes.DtoMerger()
            val networkMerger = cdd.routes.NetworkMerger()
            val networkGenerator = cdd.routes.NetworkGenerator()
                        val networkParser = cdd.routes.NetworkParser()
            val mocksEmit = cdd.mocks.MocksEmit()
            val mocksParse = cdd.mocks.MocksParse()
            val testsEmit = cdd.tests.TestsEmit()
            val testsParse = cdd.tests.TestsParse()
            val funcsEmit = cdd.functions.FunctionsEmit()
            val funcsParse = cdd.functions.FunctionsParse()

            mocksParse.parse()
            testsParse.parse()
            funcsParse.parse()

            // 1. Merge DTOs
            println("Merging Models...")
            val dtoFiles = srcDir.walk().filter { it.isFile && it.extension == "kt" }.toList()
            document.components?.schemas?.forEach { (schemaName, schema) ->
                val enrichedSchema = schema.copy(name = schemaName)
                val targetFile = dtoFiles.find { it.name == "$schemaName.kt" }
                if (targetFile != null) {
                    val existingCode = targetFile.readText()
                    try {
                        val mergedCode = dtoMerger.mergeDto(existingCode, enrichedSchema)
                        if (mergedCode != existingCode) {
                            targetFile.writeText(mergedCode)
                            println("  Updated $schemaName in ${targetFile.name}")
                        }
                    } catch (e: Exception) {
                        println("  Failed to merge $schemaName: ${e.message}\nCODE WAS:\n$existingCode")
                    }
                }
            }

            // 2. Merge Network Clients
            println("Merging Network Clients...")
            val endpointsByTag = document.paths.flatMap { (path, item) ->
                val list = mutableListOf<cdd.openapi.EndpointDefinition>()
                item.get?.let { list.add(it) }
                item.post?.let { list.add(it) }
                item.put?.let { list.add(it) }
                item.delete?.let { list.add(it) }
                item.options?.let { list.add(it) }
                item.head?.let { list.add(it) }
                item.patch?.let { list.add(it) }
                item.trace?.let { list.add(it) }
                list
            }.groupBy { it.tags.firstOrNull() ?: "Default" }

            val apiFiles = srcDir.walk().filter { it.isFile && it.extension == "kt" && it.name.endsWith("Api.kt") }.toList()
            
            endpointsByTag.forEach { (tag, specEndpoints) ->
                val safeName = tag.replace(Regex("[^a-zA-Z0-9]"), "").replaceFirstChar { it.uppercase() } + "Api"
                val targetFile = apiFiles.find { it.name == "${safeName}.kt" }
                
                if (targetFile != null) {
                    val existingCode = targetFile.readText()
                    try {
                        val existingEndpoints = networkParser.parse(existingCode)
                        val mergedEndpoints = networkMerger.mergeEndpoints(existingEndpoints, specEndpoints)
                        
                        val packageName = existingCode.lines().find { it.startsWith("package ") }?.removePrefix("package ")?.trim() ?: "api"
                        
                        val ktFile = networkGenerator.generateApi(packageName, safeName, mergedEndpoints, document.servers)
                        targetFile.writeText(ktFile.text)
                        println("  Updated ${safeName}.kt")
                    } catch (e: Exception) {
                        println("  Failed to merge $safeName: ${e.message}")
                    }
                }
            }
            
            println("Merge complete.")
        } catch (e: Exception) {
            println("❌ merge_openapi failed: ${e.message}")
            e.printStackTrace()
        } finally {
            org.jetbrains.kotlin.com.intellij.openapi.util.Disposer.dispose(disposable)
        }
    }
}

/**
 * Main entry point for the cdd-kotlin executable.
 * @param args The command line arguments
 */
 
/**
 * Subcommand to generate API documentation code examples as JSON.
 */
class ToDocsJson : CliktCommand(name = "to_docs_json", help = "Generate API documentation code examples as JSON") {
    /** Input OpenAPI specification file or URL. */
    val input by option("-i", "--input", help = "Path or URL to the OpenAPI specification").required()
    /** Omit the imports field. */
    val noImports by option("--no-imports", help = "Omit the imports field").flag()
    /** Omit the wrapper_start and wrapper_end fields. */
    val noWrapping by option("--no-wrapping", help = "Omit the wrapper_start and wrapper_end fields").flag()

    /** Executes the to_docs_json logic. */
    override fun run() {
        try {
            val parser = cdd.openapi.OpenApiParser()
            val file = File(input)
            val document = parser.parseFile(file)
            
            val operationsList = mutableListOf<Map<String, Any>>()
            
            document.paths.forEach { (path, item) ->
                val methods = mapOf(
                    "GET" to item.get,
                    "PUT" to item.put,
                    "POST" to item.post,
                    "DELETE" to item.delete,
                    "OPTIONS" to item.options,
                    "HEAD" to item.head,
                    "PATCH" to item.patch,
                    "TRACE" to item.trace
                )
                
                methods.forEach { (methodName, op) ->
                    if (op != null) {
                        val operationId = op.operationId
                        val tag = op.tags.firstOrNull() ?: "Default"
                        val apiClassName = tag.replace(Regex("[^a-zA-Z0-9]"), "").replaceFirstChar { it.uppercase() } + "Api"
                        
                        val methodNameCamel = if (operationId.isNotBlank()) {
                            operationId
                        } else {
                            methodName.lowercase() + path.replace(Regex("[^a-zA-Z0-9]"), "").replaceFirstChar { it.uppercase() }
                        }
                        
                        val code = mutableMapOf<String, String>()
                        
                        if (!noImports) {
                            code["imports"] = """import io.ktor.client.HttpClient
import com.example.auto.api.$apiClassName"""
                        }
                        if (!noWrapping) {
                            code["wrapper_start"] = """suspend fun main() {
    val client = HttpClient()
    val api = $apiClassName(client)"""
                            code["wrapper_end"] = "}"
                        }
                        
                        // construct snippet based on parameters
                        val params = op.parameters.map { it.name + " = TODO()" }
                        val requestBodyArg = if (op.requestBody != null) "body = TODO()" else null
                        val allArgs = (params + listOfNotNull(requestBodyArg)).joinToString(", ")
                        
                        code["snippet"] = "    val response = api.${methodNameCamel}($allArgs)"
                        
                        operationsList.add(mapOf(
                            "method" to methodName,
                            "path" to path,
                            "operationId" to operationId,
                            "code" to code
                        ))
                    }
                }
            }
            
            val outputJson = mapOf(
                "language" to "kotlin",
                "operations" to operationsList
            )
            
            val mapper = com.fasterxml.jackson.databind.ObjectMapper()
            println(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(listOf(outputJson)))
            
        } catch (e: Exception) {
            System.err.println("Error generating docs: ${e.message}")
            e.printStackTrace()
        }
    }
}


fun main(args: Array<String>) {
    CddKotlin().subcommands(FromOpenApi(), ToOpenApi(), MergeOpenApi(), ToDocsJson()).main(args)
}
