name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build WASM
      run: echo "WASM build is not possible"
      
    - name: Build Distribution
      run: ./gradlew installDist

    - name: Package Distributions
      run: |
        tar -czvf cdd-kotlin-linux.tar.gz -C build/install/cdd-kotlin .

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cdd-kotlin-linux.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
